"""Initial migration

Revision ID: 060c7d0e42de
Revises: 098e4bfb065d
Create Date: 2025-10-07 23:24:38.720773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060c7d0e42de'
down_revision = '098e4bfb065d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    op.drop_constraint('time_slots_ibfk_2', 'time_slots', type_='foreignkey')
    op.drop_constraint('time_slots_ibfk_1', 'time_slots', type_='foreignkey')
    
    # Then drop the index
    op.drop_index('idx_trainer_date', table_name='time_slots')
    
    # Create new index
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    
    # Recreate foreign key constraints
    op.create_foreign_key(None, 'time_slots', 'trainers', ['trainer_id'], ['id'])
    op.create_foreign_key(None, 'time_slots', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.create_foreign_key('time_slots_ibfk_1', 'time_slots', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('time_slots_ibfk_2', 'time_slots', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.create_index('idx_trainer_date', 'time_slots', ['trainer_id', 'date'], unique=False)
    # ### end Alembic commands ###












