"""Add locked_until field to TimeSlot for booking conflict prevention

Revision ID: 098e4bfb065d
Revises: 651f5e866efd
Create Date: 2025-10-07 23:08:56.900446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098e4bfb065d'
down_revision = '651f5e866efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new column first
    op.add_column('time_slots', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    
    # Drop foreign key constraints first
    op.drop_constraint('time_slots_ibfk_2', 'time_slots', type_='foreignkey')
    op.drop_constraint('time_slots_ibfk_1', 'time_slots', type_='foreignkey')
    
    # Then drop the index
    op.drop_index('idx_trainer_date', table_name='time_slots')
    
    # Create new index
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    
    # Recreate foreign key constraints
    op.create_foreign_key(None, 'time_slots', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'time_slots', 'trainers', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.create_foreign_key('time_slots_ibfk_1', 'time_slots', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('time_slots_ibfk_2', 'time_slots', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.create_index('idx_trainer_date', 'time_slots', ['trainer_id', 'date'], unique=False)
    op.drop_column('time_slots', 'locked_until')
    # ### end Alembic commands ###












