"""Initial migration

Revision ID: 0e15ba00a93c
Revises: 702a54793e02
Create Date: 2025-10-08 00:29:53.570812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e15ba00a93c'
down_revision = '702a54793e02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###












