"""Add TrainerAvailability model

Revision ID: 3848ce760e30
Revises: 
Create Date: 2025-09-28 17:20:16.622800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3848ce760e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('preferred_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('preferred_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('preferred_times', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('confirmed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('recurring_pattern', sa.String(length=50), nullable=True))
    op.alter_column('bookings', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'),
               existing_nullable=True)
    op.drop_column('bookings', 'preferred_dates')
    op.add_column('sessions', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('client_rating', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('trainer_rating', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('client_feedback', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('trainer_feedback', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'trainer_feedback')
    op.drop_column('sessions', 'client_feedback')
    op.drop_column('sessions', 'trainer_rating')
    op.drop_column('sessions', 'client_rating')
    op.drop_column('sessions', 'actual_end_time')
    op.drop_column('sessions', 'actual_start_time')
    op.drop_column('sessions', 'booking_id')
    op.add_column('bookings', sa.Column('preferred_dates', mysql.TEXT(), nullable=True))
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('bookings', 'recurring_pattern')
    op.drop_column('bookings', 'is_recurring')
    op.drop_column('bookings', 'priority_score')
    op.drop_column('bookings', 'confirmed_date')
    op.drop_column('bookings', 'preferred_times')
    op.drop_column('bookings', 'preferred_end_date')
    op.drop_column('bookings', 'preferred_start_date')
    # ### end Alembic commands ###





