"""Add requested time fields to booking requests

Revision ID: 702a54793e02
Revises: 060c7d0e42de
Create Date: 2025-10-07 23:49:31.782969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702a54793e02'
down_revision = '060c7d0e42de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###












